# **Silver Layer - Handling/ cleaning data**

### **Imporing libraries**

In [869]:
import pandas as pd
import numpy as np

### **Reading data**

Read bronze layer data

In [870]:
Silver_df = pd.read_csv("/Users/folder/project_real_estate/data/raw/Bronze.csv")

### **Configure pandas display settings**

In [871]:
pd.options.display.float_format = '{:,.2f}'.format
pd.options.display.max_rows = None
pd.options.display.max_columns = None

In [872]:
Silver_df.head()

,url,price,description,location,type,size,bedrooms,bathrooms,available_from,payment_method,down_payment
0,https://www.propertyfinder.eg/en/plp/buy/chale...,"8,000,000",OWN A CHALET IN EL GOUNA WITH A PRIME LOCATION...,"Swan Lake Gouna, Al Gouna, Hurghada, Red Sea",Chalet,732 sqft / 68 sqm,1+ Maid,1,31 Aug 2025,Cash,"1,200,000 EGP"
1,https://www.propertyfinder.eg/en/plp/buy/villa...,"25,000,000","For sale, a villa with immediate delivery in C...","Karmell, New Zayed City, Sheikh Zayed City, Giza",Villa,"2,368 sqft / 220 sqm",4,4,2 Sep 2025,Cash,"2,100,000 EGP"
2,https://www.propertyfinder.eg/en/plp/buy/chale...,"15,135,000","With a down payment of EGP 1,513,000, a fully ...","Azha North, Ras Al Hekma, North Coast",Chalet,"1,270 sqft / 118 sqm",2,2,19 Aug 2025,Cash,"1,513,000 EGP"
3,https://www.propertyfinder.eg/en/plp/buy/apart...,"12,652,000",Own an apartment in New Cairo with a minimal d...,"Taj City, 5th Settlement Compounds, The 5th Se...",Apartment,"1,787 sqft / 166 sqm",3,2,26 Aug 2025,Installments,"1,260,000 EGP"
4,https://www.propertyfinder.eg/en/plp/buy/villa...,"45,250,000",Project: Granville\nLocation: Fifth Settlement...,"Granville, New Capital City, Cairo",Villa,"4,306 sqft / 400 sqm",7,7,2 Sep 2025,Cash,"2,262,500 EGP"

### **Cleaning data**

#### Check duplicate rows

In [873]:
# Total duplicate rows
duplicate_rows = Silver_df.duplicated().sum()

print(f"Duplicate rows: {duplicate_rows}")

Duplicate rows: 0

#### URL

In [874]:
print("Duplicate rows:", Silver_df.duplicated().sum())

print("Duplicate URLs:", Silver_df["url"].duplicated().sum())

Duplicate rows: 0
Duplicate URLs: 0

In [875]:
# Convert to string and remove extra spaces
Silver_df["url"] = (
    Silver_df["url"]
    .astype("string")
    .str.strip()
)

# Ensure URLs start with https://
Silver_df["url"] = Silver_df["url"].str.replace(
    r"^http://",
    "https://",
    regex=True
)

missing_url = Silver_df["url"].isna() | (Silver_df["url"].str.strip() == "")

# Remove duplicate listings based on URL
# Rows with a valid URL
with_url = Silver_df[~missing_url]

# Rows without a URL
without_url = Silver_df[missing_url]

# Remove duplicate URLs only
with_url = with_url.drop_duplicates(subset=["url"])

# Combine everything back
Silver_df = pd.concat([with_url, without_url], ignore_index=True)

#### price

In [876]:
Silver_df["price"] = (
    Silver_df["price"]
    .str.replace(",", "", regex=False)
    .astype("Int64")
)

In [877]:
Silver_df.nsmallest(
    10,
    "price"
)[["price"]]

        price
15671  186900
454    200000
3538   202500
7507   233766
13041  285000
7489   300000
132    325000
190    325000
438    325000
2605   325000

In [878]:
Silver_df.nlargest(
    10,
    "price"
)[["price"]]

           price
14762  840000000
12670  650000000
18560  453000000
12051  400000000
13447  400000000
15066  400000000
9871   375000000
13068  375000000
12370  374000000
11523  360000000

In [879]:
Silver_df["price"].describe(percentiles=[0.01,0.05,0.25,0.5,0.75,0.95,0.99])

count        19,385.00
mean     16,415,306.81
std      23,697,908.14
min         186,900.00
1%        1,370,000.00
5%        2,700,000.00
25%       6,000,000.00
50%      10,345,550.00
75%      18,169,000.00
95%      47,852,500.00
99%     100,000,000.00
max     840,000,000.00
Name: price, dtype: Float64

#### description

1 *Remove extra spaces*
2 *Remove repeated new lines*
3 *Strip whitespace*

In [880]:
Silver_df["description"] = (
    Silver_df["description"]
    .str.replace("\n", " ", regex=False)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

#### Location

In [881]:
def split_location(location):
    if pd.isna(location):
        return pd.Series(
            [np.nan, np.nan, np.nan, np.nan],
            index=["compound", "district", "city", "governorate"]
        )

    parts = [p.strip() for p in str(location).split(",")]

    # -------------------------------------
    # Pattern: Compound, Governorate
    # Example:
    # Madinaty, Cairo
    # -------------------------------------
    if len(parts) == 2:
        return pd.Series(
            [parts[0], np.nan, np.nan, parts[1]],
            index=["compound", "district", "city", "governorate"]
        )

    # -------------------------------------
    # Pattern: Compound, City, Governorate
    # Example:
    # Marassi, Sidi Abdel Rahman, North Coast
    #
    # OR
    #
    # Compound, District, Governorate
    # Example:
    # Silver Sands, Qesm Marsa Matrouh, North Coast
    # -------------------------------------
    elif len(parts) == 3:

        second = parts[1].lower()

        if second.startswith("qesm"):
            district = parts[1]
            city = np.nan
        else:
            district = np.nan
            city = parts[1]

        return pd.Series(
            [parts[0], district, city, parts[2]],
            index=["compound", "district", "city", "governorate"]
        )

    # -------------------------------------
    # Pattern: Compound, District, City, Governorate
    # Example:
    # Mangroovy Residence, Al Gouna, Hurghada, Red Sea
    # -------------------------------------
    elif len(parts) == 4:

        return pd.Series(
            [parts[0], parts[1], parts[2], parts[3]],
            index=["compound", "district", "city", "governorate"]
        )

    # -------------------------------------
    # Pattern: Compound, District, Area..., Governorate
    # Example:
    # Mountain View iCity,
    # 5th Settlement Compounds,
    # The 5th Settlement,
    # New Cairo City,
    # Cairo
    # -------------------------------------
    elif len(parts) > 4:

        city = ", ".join(parts[2:-1])

        return pd.Series(
            [parts[0], parts[1], city, parts[-1]],
            index=["compound", "district", "city", "governorate"]
        )

    # -------------------------------------
    # Pattern: Compound only
    # -------------------------------------
    else:

        return pd.Series(
            [parts[0], np.nan, np.nan, np.nan],
            index=["compound", "district", "city", "governorate"]
        )


Silver_df[
    ["compound", "district", "city", "governorate"]
] = Silver_df["location"].apply(split_location)

In [882]:
Silver_df = Silver_df.drop(columns=["location"])

In [883]:
Silver_df["compound"].value_counts(dropna=False)

compound
Marassi                                                   433
Mountain View iCity                                       393
Madinaty                                                  368
Hyde Park                                                 359
Palm Hills New Cairo                                      322
Silver Sands                                              299
O West                                                    283
Sarai                                                     267
Mountain View iCity October                               257
Mivida                                                    242
Mountain View                                             239
Mangroovy Residence                                       228
Taj City                                                  225
Azha North                                                221
Mountain View Hyde Park                                   218
Mesca                                                     200
Fouka Bay                                                 198
El Patio Oro                                              175
Makadi Orascom Resort                                     173
Badya Palm Hills                                          172
Marsa Baghush                                             165
City Gate                                                 160
Villette                                                  157
Ramla Lakeside                                            154
Sodic East                                                145
Almaza Bay                                                145
Mazarine                                                  142
New Giza                                                  137
Seashore                                                  130
Al Burouj Compound                                        128
Lake View Residence                                       124
June                                                      124
Moon Residences                                           119
Hacienda Bay                                              119
Village West                                              116
Amwaj                                                     115
Eastown                                                   113
The Med                                                   109
Bait Alwatan                                              108
Swan Lake Residence                                       107
Soul North Coast                                          100
Allegria                                                   99
Palm Parks   Palm Hills                                    97
Salt                                                       97
Park Side Residence                                        96
Caesar                                                     94
Latin District                                             93
NaN                                                        91
La Vista City                                              91
Vye Sodic                                                  90
Hacienda West                                              90
Beit Al Bahr                                               87
IL Monte Galala                                            85
Gaia                                                       82
Playa Resort                                               80
Galleria Moon Valley                                       79
Cali Coast                                                 78
L'avenir                                                   76
Mountain View 1.1                                          76
Al Khamayel city                                           76
Al Masyaf                                                  75
ARC of Soma                                                75
Hacienda Waters                                            74
Zed East                                                   74
Seashell                                                   73
Golf Porto Marina                                          73
The Square                                                 71
El Hadaba District                                         69
Belle Vie                                                  68
Al Maqsad                                                  68
Stone Residence                                            68
Swan Lake North Coast                                      67
Direction White                                            66
Azha                                                       66
Jefaira                                                    65
Etapa                                                      64
The Crown                                                  64
Ogami                                                      63
Palm Hills Golf Extension                                  62
HAP Town                                                   62
Hacienda Heneish                                           60
The Estates                                                60
Six West                                                   59
Telal Al Sokhna                                            59
Blanca Gardens                                             58
Koun                                                       57
District 5                                                 57
Joulz                                                      55
Kayan                                                      54
Cairo Festival City                                        53
Solana                                                     52
Creek Town                                                 52
Zayed Dunes                                                51
D-Bay                                                      51
Marina 5                                                   50
La vista Ras El Hikma                                      48
Telal Alamein                                              48
The Address East                                           48
Bay West                                                   48
Plage                                                      47
Katameya Dunes                                             47
La Vista Bay                                               47
Solare                                                     47
Mountain View October Park                                 46
Al Ahyaa District                                          46
Saada Compound                                             43
Mar Bay                                                    43
Capital Gardens   Palm Hills                               42
Mountain View Chill Out Park                               42
Swan Lake Gouna                                            40
Hacienda White                                             40
Sun Capital                                                39
Panorama                                                   39
Talala                                                     39
90 Avenue                                                  39
Aliva                                                      38
El Rehab Extension                                         38
Stone Park                                                 38
Summer                                                     38
Beit Alwatan                                               37
Grand Heights                                              37
Noor City                                                  37
El Narges Buildings                                        36
Lake View Residence 2                                      36
El Motamayez District                                      36
Al Andalus Buildings                                       36
TRIO                                                       36
Swan Lake West                                             35
Bloomfields                                                35
Magawish Resort                                            35
Patio Al Zahraa                                            34
Azzar 2                                                    34
Kamaran                                                    33
LVLS By Mountain View                                      33
Westown                                                    33
Wadi Jebal                                                 33
Green Revolution                                           32
Magawish                                                   31
Ivoire                                                     31
The Icon Residence                                         31
Karmell                                                    31
Al  Rabwa                                                  31
Soma Breeze                                                30
Layan Residence                                            30
Nyoum October                                              30
Golf Town-Marina Edition                                   29
The brooks                                                 29
Royal City                                                 29
Rock Eden                                                  28
Storia Del Mare                                            28
Atalantis                                                  28
Les Rois                                                   28
Marina 8                                                   28
Palm Hills Village Gate                                    28
The Gate Towers                                            27
South Med                                                  27
October Plaza                                              27
North Edge Towers                                          27
Cornish El Nile St.                                        27
El Kawther District                                        27
Katameya Heights                                           26
Green Square                                               26
PX Palm Hills                                              26
South Lotus                                                26
Palm Hills Kattameya                                       25
Veranda                                                    25
Promenade New Cairo                                        25
Upville                                                    25
Alex West                                                  25
Youd                                                       25
Telal East                                                 24
Tawny Hyde Park                                            24
AlKarma Kay                                                24
Palm Hills Golf Views                                      24
Zoya                                                       24
El Patio Vida                                              24
Vee Sawari                                                 24
Aeon                                                       23
Azad                                                       23
Marseilia Beach 5                                          22
Village Gardens Katameya                                   22
Seazen                                                     22
Atrio                                                      21
Celesta Hills                                              21
Garden Lakes                                               21
La Vista 6                                                 21
Royal Meadows                                              21
Lake View                                                  21
Al Lebeny Axis                                             21
Sodic West                                                 21
Jirian                                                     21
JAYD Residence                                             21
Azzar                                                      20
Mountain View 4                                            20
Crescent Walk                                              20
Alma                                                       19
Pyramids Heights                                           19
Palm Hills                                                 19
Marriott Residence Heliopolis                              19
Al Bostan St.                                              19
Ashgar City                                                19
Bianchi                                                    19
El Banafseg Apartment Buildings                            19
La Vista Cascada                                           19
Al Geish Road                                              18
Levana                                                     18
Gate 4 - Mena                                              18
Ras Soma                                                   18
Regents Park                                               18
The Waterway View                                          18
The Butterfly                                              18
El Patio Town                                              18
Pyramids Hills                                             18
Elan                                                       18
Jannat October                                             18
Palm Hills October                                         17
Naia bay                                                   17
Tawila El Gouna                                            17
Ghazala Bay                                                17
Dyar Park                                                  17
Lake West                                                  17
Safia                                                      17
Dose                                                       17
Fifth Square                                               17
V Levels                                                   16
Solana East                                                16
Skala Mountain View Ras El Hikma                           16
Amorada New Cairo                                          16
DeJoya Residence                                           16
Palm City                                                  16
Arabia Area                                                16
Aroma Residence                                            16
ZAT                                                        16
Rivers                                                     16
One Kattameya                                              16
Downtown                                                   16
Villar                                                     16
Reve Du Nil                                                16
The Fourteen Golf Residences                               15
The Grand Resort                                           15
Al Andalus El Gedida                                       15
Village Views                                              15
Hand villa                                                 15
Westview Residence                                         15
Cape Bay Sokhna                                            15
The Address                                                15
Janna 2                                                    15
Palm Hills WoodVille                                       15
Ever                                                       14
New Garden City                                            14
9th District                                               14
Eden                                                       14
The Sierras                                                14
Lasirena Palm Beach                                        14
The MarQ Gardens                                           14
Glee                                                       14
Casa                                                       14
Sahl Hasheesh Resort                                       14
Blumar                                                     14
Tag Sultan                                                 14
Al Hadaba Al Wosta                                         14
IL Bosco                                                   13
Stoda                                                      13
The Crest                                                  13
Beverly Hills Road                                         13
Patio Casa                                                 13
Cleopatra Square                                           13
Muruj                                                      13
Tara                                                       13
Forty West                                                 13
Hadayek Al Mohandessin                                     13
New Alamein City                                           13
Terrace Compound                                           13
Lasirena Mini Egypt                                        13
Opera City                                                 12
Azzurra Resort                                             12
West Somid Road                                            12
New Narges                                                 12
LYV                                                        12
Hawaiian                                                   12
Palm Hills Katameya Extension                              12
Tala                                                       12
Al Patio                                                   12
Bamboo Palm Hills                                          12
Reef Town                                                  12
Bella Vento Galala                                         12
Zed Towers                                                 12
Qamary                                                     12
Stella Heliopolis                                          12
Obour City                                                 12
Maadi View                                                 12
1st Neighborhood                                           12
Hanging Gardens                                            12
Caribbean Bay                                              11
Glen                                                       11
Smouha                                                     11
The Lakeview Boutique Villas                               11
Bellagio                                                   11
Keeva                                                      11
Degla Palms                                                11
North Lotus                                                11
Jasmine Palace Resort                                      11
Beit Al Watan                                              11
Jeera                                                      11
Zayed 2000                                                 11
Yasmine District                                           11
The Courtyards                                             11
Zayed Regency                                              11
Joya                                                       11
New Lotus                                                  11
Caesar Island                                              10
Ever New Cairo                                             10
IL Bosco City                                              10
Remal                                                      10
Soleya                                                     10
Beverly Hills                                              10
Arkan Palm 205                                             10
Jasmine Village                                            10
Mountain View Giza Plateau                                 10
El Koronfel                                                10
Princess Resort                                            10
Okarida                                                    10

#### type

In [884]:
Silver_df["type"].value_counts(dropna=False)

type
Apartment          8355
Chalet             4038
Villa              3570
Townhouse          1335
Twin House          834
Duplex              622
Penthouse           569
iVilla              268
Hotel Apartment     104
NaN                  77
Land                 63
Cabin                38
Palace               23
Whole Building       14
Roof                  6
Full Floor            4
Bulk Sale Unit        3
Bungalow              1
Name: count, dtype: int64

In [885]:
Silver_df["type"] = (
    Silver_df["type"]
    .astype("string")
    .str.strip()
    .str.title()
    .replace({
        "Ivilla": "iVilla"
    })
    .astype("category")
)

In [886]:
Silver_df["type"].value_counts(dropna=False)

type
Apartment          8355
Chalet             4038
Villa              3570
Townhouse          1335
Twin House          834
Duplex              622
Penthouse           569
iVilla              268
Hotel Apartment     104
<NA>                 77
Land                 63
Cabin                38
Palace               23
Whole Building       14
Roof                  6
Full Floor            4
Bulk Sale Unit        3
Bungalow              1
Name: count, dtype: int64

In [887]:
Silver_df["type"] = (
    Silver_df["type"]
    .cat.add_categories(["Unknown"])
    .fillna("Unknown")
)

#### size

In [888]:
# Extract square feet
Silver_df["size_sqft"] = (
    Silver_df["size"]
    .str.extract(r'([\d,]+)\s*sqft')[0]
    .str.replace(",", "", regex=False)
    .astype("Int64")
)

# Extract square meters
Silver_df["size_sqm"] = (
    Silver_df["size"]
    .str.extract(r'/\s*([\d,]+)\s*sqm')[0]
    .str.replace(",", "", regex=False)
    .astype("Int64")
)

In [889]:
print(Silver_df[["size", "size_sqft", "size_sqm"]].head())

                   size  size_sqft  size_sqm
0     732 sqft / 68 sqm        732        68
1  2,368 sqft / 220 sqm       2368       220
2  1,270 sqft / 118 sqm       1270       118
3  1,787 sqft / 166 sqm       1787       166
4  4,306 sqft / 400 sqm       4306       400

In [890]:
Silver_df["size_sqft"].describe()

count        19,847.00
mean         11,135.95
std       1,208,324.15
min              11.00
25%           1,367.00
50%           1,830.00
75%           2,594.00
max     170,195,636.00
Name: size_sqft, dtype: Float64

In [891]:
Silver_df[Silver_df["size_sqm"] < 20]

,url,price,description,type,size,bedrooms,bathrooms,available_from,payment_method,down_payment,compound,district,city,governorate,size_sqft,size_sqm
2693,https://www.propertyfinder.eg/en/plp/buy/villa...,39000000,"Villa for sale in Madinaty, one of the best ar...",Villa,22 sqft / 2 sqm,5+ Maid,4,6 Aug 2025,Cash,"12,000,000 EGP",Madinaty,NaN,NaN,Cairo,22,2
14334,https://www.propertyfinder.eg/en/plp/buy/chale...,1081500,دلوقتي عندك فرصة تمتلك ستوديو أنيق في جولف مار...,Chalet,11 sqft / 1 sqm,studio,1,28 Aug 2025,Cash,NaN,Al Alamein,NaN,NaN,North Coast,11,1

In [892]:
Silver_df = Silver_df[Silver_df["size_sqm"] >= 20]

In [893]:
print("Missing sqft:", Silver_df["size_sqft"].isna().sum())
print("Missing sqm :", Silver_df["size_sqm"].isna().sum())

Missing sqft: 0
Missing sqm : 0

In [894]:
missing_size = Silver_df["size_sqm"].isna().sum()

print(f"Missing size records: {missing_size}")
print(f"Missing percentage: {missing_size / len(Silver_df) * 100:.2f}%")

Missing size records: 0
Missing percentage: 0.00%

In [895]:
Silver_df.drop(columns=["size"], inplace=True)

In [896]:
print(Silver_df[["size_sqft", "size_sqm"]].dtypes)

size_sqft    Int64
size_sqm     Int64
dtype: object

In [897]:
Silver_df.nsmallest(
    10,
    "size_sqm"
)[["size_sqm", "size_sqm", "compound", "city"]]

       size_sqm  size_sqm           compound               city
14774        20        20             Ivoire  Sheikh Zayed City
9824         27        27              Zahra  Sidi Abdel Rahman
4803         29        29    Valencia Valley     New Cairo City
185          30        30  Golf Porto Marina         Al Alamein
527          30        30  Golf Porto Marina         Al Alamein
1367         30        30               Glee                NaN
2877         30        30  Golf Porto Marina         Al Alamein
2999         30        30  Golf Porto Marina         Al Alamein
3014         30        30  Golf Porto Marina         Al Alamein
4269         30        30  Golf Porto Marina         Al Alamein

In [898]:
Silver_df.nlargest(
    10,
    "size_sqm"
)[["size_sqm", "price", "compound", "city"]]

       size_sqm      price            compound                          city
4410   15811692   11692311               Sarai  Mostakbal City - Future City
8277     302400       <NA>  The 6th Settlement                New Cairo City
15510     96106    6550000       Mountain View                  Ras Al Hekma
794       27500  300000000    Green Revolution             Sheikh Zayed City
15204     21000  130200000      New Zayed City             Sheikh Zayed City
9669       9500       <NA>    Hood 11 Side St.                6 October City
18512      8400       <NA>    Green Revolution             Sheikh Zayed City
8174       6779    3500000      Sidi Gaber St.                     Hay Sharq
13451      4200       <NA>    Green Revolution             Sheikh Zayed City
12670      3800  650000000    Katameya Heights   El Katameya, New Cairo City

#### bedrooms

In [899]:
Silver_df["bedrooms"].value_counts(dropna=False)

bedrooms
3               4959
3+ Maid         3737
2               2849
4+ Maid         2126
2+ Maid         1748
4               1126
5+ Maid          785
1                751
1+ Maid          447
5                325
studio           279
6+ Maid          254
7+ Maid          128
6                 93
NaN               67
7++ Maid          67
studio+ Maid      48
7                 33
7+                23
Name: count, dtype: int64

In [900]:
Silver_df = (
    Silver_df
    .rename(columns={"bedrooms": "bedrooms_raw"})
    .assign(
        # Maid room indicator
        maid_room=lambda df: (
            df["bedrooms_raw"]
            .astype("string")
            .str.contains("Maid", case=False, na=False)
            .astype("boolean")
        ),

        # Extract bedroom count
        bedrooms=lambda df: (
            df["bedrooms_raw"]
            .astype("string")
            .str.extract(r"(\d+)")[0]
            .astype("Int64")
        )
    )
)

# Convert studios to 0 bedrooms
Silver_df.loc[
    Silver_df["bedrooms_raw"].str.contains("studio", case=False, na=False),
    "bedrooms"
] = 0

In [901]:
# Drop the original column after validation
Silver_df = Silver_df.drop(columns="bedrooms_raw")

In [902]:
Silver_df["bedrooms"].value_counts(dropna=False)

bedrooms
3       8696
2       4597
4       3252
1       1198
5       1110
6        347
0        327
7        251
<NA>      67
Name: count, dtype: Int64

#### bathrooms

In [903]:
Silver_df["bathrooms"].value_counts(dropna=False)

bathrooms
3       6562
2       5529
4       3280
1       2096
5       1313
6        463
7        223
7+       159
NaN       63
2.0       48
3.0       48
1.0       21
4.0       19
5.0       11
none       5
6.0        3
7.0        2
Name: count, dtype: int64

In [904]:
Silver_df = (
    Silver_df
    .rename(columns={"bathrooms": "bathrooms_raw"})
    .assign(
        bathrooms_plus=lambda df: (
            df["bathrooms_raw"]
            .astype("string")
            .str.contains(r"\+", regex=True, na=False)
            .astype("boolean")
        ),

        bathrooms=lambda df: (
            df["bathrooms_raw"]
            .astype("string")
            .str.strip()
            .replace({"none": pd.NA})
            .str.extract(r"(\d+)")[0]
            .astype("Int64")
        )
    )
)

In [905]:
# Drop the original column after validation
Silver_df = Silver_df.drop(columns="bathrooms_raw")

In [906]:
Silver_df["bathrooms"].value_counts(dropna=False)

bathrooms
3       6610
2       5577
4       3299
1       2117
5       1324
6        466
7        384
<NA>      68
Name: count, dtype: Int64

#### available_from

In [907]:
Silver_df.head()

,url,price,description,type,available_from,payment_method,down_payment,compound,district,city,governorate,size_sqft,size_sqm,maid_room,bedrooms,bathrooms_plus,bathrooms
0,https://www.propertyfinder.eg/en/plp/buy/chale...,8000000,OWN A CHALET IN EL GOUNA WITH A PRIME LOCATION...,Chalet,31 Aug 2025,Cash,"1,200,000 EGP",Swan Lake Gouna,Al Gouna,Hurghada,Red Sea,732,68,True,1,False,1
1,https://www.propertyfinder.eg/en/plp/buy/villa...,25000000,"For sale, a villa with immediate delivery in C...",Villa,2 Sep 2025,Cash,"2,100,000 EGP",Karmell,New Zayed City,Sheikh Zayed City,Giza,2368,220,False,4,False,4
2,https://www.propertyfinder.eg/en/plp/buy/chale...,15135000,"With a down payment of EGP 1,513,000, a fully ...",Chalet,19 Aug 2025,Cash,"1,513,000 EGP",Azha North,NaN,Ras Al Hekma,North Coast,1270,118,False,2,False,2
3,https://www.propertyfinder.eg/en/plp/buy/apart...,12652000,Own an apartment in New Cairo with a minimal d...,Apartment,26 Aug 2025,Installments,"1,260,000 EGP",Taj City,5th Settlement Compounds,"The 5th Settlement, New Cairo City",Cairo,1787,166,False,3,False,2
4,https://www.propertyfinder.eg/en/plp/buy/villa...,45250000,"Project: Granville Location: Fifth Settlement,...",Villa,2 Sep 2025,Cash,"2,262,500 EGP",Granville,NaN,New Capital City,Cairo,4306,400,False,7,False,7

In [908]:
Silver_df["available_from"] = pd.to_datetime(
    Silver_df["available_from"],
    format="%d %b %Y",
    errors="coerce"
)

In [909]:
print(Silver_df["available_from"].dtype)

datetime64[ns]

#### payment_method

In [910]:
Silver_df["payment_method"].value_counts(dropna=False)

payment_method
Cash            15519
Installments     3862
NaN               464
Name: count, dtype: int64

In [911]:
Silver_df["payment_method"] = (
    Silver_df["payment_method"]
    .astype("string")
    .str.strip()
    .str.title()
)

In [912]:
Silver_df["payment_method"] = Silver_df["payment_method"].astype("category")

In [913]:
Silver_df["payment_method"].dtype

CategoricalDtype(categories=['Cash', 'Installments'], ordered=False, categories_dtype=string)

In [914]:
Silver_df["payment_method"] = (
    Silver_df["payment_method"]
    .cat.add_categories(["Unknown"])
    .fillna("Unknown")
)

In [915]:
Silver_df["payment_method"].value_counts(dropna=False)

payment_method
Cash            15519
Installments     3862
Unknown           464
Name: count, dtype: int64

#### down_payment

In [916]:
Silver_df["down_payment"] = (
    Silver_df["down_payment"]
        .astype("string")
        .str.replace("EGP", "", regex=False)
        .str.replace(",", "", regex=False)
        .str.strip()
)

Silver_df["down_payment"] = pd.to_numeric(
    Silver_df["down_payment"],
    errors="coerce"
).astype("Int64")

In [917]:
Silver_df["down_payment"].describe()

count         5,444.00
mean      1,979,201.60
std       3,866,547.91
min               1.00
25%         483,541.25
50%         941,500.00
75%       2,032,125.00
max     150,000,000.00
Name: down_payment, dtype: Float64

In [918]:
Silver_df["down_payment"].value_counts(dropna=False)

down_payment
<NA>         14401
100000         203
5              131
1              102
500000          94
1000000         93
1500000         76
800000          67
300000          62
2000000         61
600000          61
750000          58
550000          55
650000          54
900000          54
3000000         54
400000          53
700000          51
1250000         50
1200000         46
450000          39
4000000         39
2500000         37
850000          36
1400000         33
1150000         33
1300000         33
1100000         32
2800000         29
1050000         27
1600000         26
10              26
3500000         25
1800000         23
20              23
2400000         23
950000          23
350000          22
6000000         22
250000          21
1900000         21
9000000         21
1700000         21
5000000         20
10000000        19
1350000         19
200000          18
1450000         18
2100000         18
625000          18
4500000         17
3200000         15
2700000         15
520000          15
1750000         14
2750000         13
3600000         13
2200000         13
410000          12
1650000         11
6500000         11
630000          11
2600000         11
7000000         11
15000000        11
1550000         11
440000          11
2250000         11
525000          10
390000          10
780000          10
3300000         10
19900000        10
420000          10
8000000         10
3250000          9
2900000          9
1950000          9
820000           9
325000           9
790000           9
340000           8
1125000          8
670000           8
320000           8
560000           8
870000           8
3900000          8
810000           8
435000           7
2300000          7
13000000         7
3                7
365000           7
540000           7
5400000          7
570000           7
5250000          7
4800000          7
960000           7
425000           7
25               7
370000           7
260000           6
1045000          6
1850000          6
775000           6
2150000          6
2350000          6
1260000          6
4300000          6
720000           6
275000           6
415000           6
1040000          6
815000           6
430000           6
230000           6
4200000          6
240000           6
705000           6
385000           6
930000           6
825000           6
980000           5
570394           5
4400000          5
795000           5
530000           5
2730949          5
2019831          5
6250000          5
1140000          5
620838           5
1220000          5
675000           5
725000           5
5500000          5
305000           5
1485000          5
225000           5
580000           5
595000           5
3750000          5
970000           5
360000           5
965000           5
50000            5
2499975          5
712083           5
1834402          5
539402           5
15               5
523902           5
2580000          5
635082           5
590000           5
150000           5
330000           5
1020000          5
4100000          5
542539           5
860000           5
660000           5
640000           5
4650000          5
1420000          5
1305000          4
9                4
462000           4
505000           4
11000000         4
585000           4
845000           4
1630000          4
2850000          4
1130000          4
5700000          4
2                4
11500000         4
680000           4
3100000          4
610000           4
355000           4
2550000          4
295000           4
3700000          4
18000000         4
100              4
740000           4
195000           4
1180000          4
1435000          4
384000           4
830000           4
545000           4
730000           4
270000           4
375000           4
455000           4
685000           4
655000           4
180000           4
1320000          4
2630000          4
10542652         4
6325591          4
1120000          4
1530000          4
490000           4
645000           4
910000           4
7500000          4
620000           4
945000           4
760000           4
3970000          4
462500           3
485000           3
5300000          3
975000           3
1225000          3
12000000         3
368000           3
290000           3
1210000          3
1792000          3
526000           3
1065000          3
8                3
2675000          3
4450000          3
1081080          3
7140000          3
3780468          3
668000           3
1012000          3
710000           3
312000           3
4950000          3
395000           3
335000           3
5177668          3
475000           3
30               3
1470000          3
1590000          3
125000           3
1416000          3
4743000          3
1560000          3
4700000          3
890000           3
7300000          3
835000           3
6750000          3
690000           3
535000           3
925000           3
615000           3
1660000          3
2650000          3
2950000          3
940000           3
210000           3
1310000          3
3800000          3
1230000          3
695000           3
468000           3
1190000          3
1460000          3
652800           3
2439000          3
2322000          3
5339740          3
280000           3
1390000          3
846000           3
4                3
1330000          3
885000           3
990000           3
1170000          3
745000           3
483750           3
4370000          3
656000           3
558000           3
16000000         3
14000000         3
405000           3
875000           3
1920000          3
465000           3
452610           3
4600000          3
90000            3
1030000          3
668220           3
1075000          3
468451           3
2450000          3
1025000          3
1295000          3
4182000          2
2160000          2
5372000          2
447000           2
4139000          2
1035000          2
380000           2
147000           2
1215500          2
514000           2
722100           2
136000           2
1752100          2
446000           2
3940870          2
1740000          2
1525000          2
5800000          2
7147500          2
635000           2
338650           2
840000           2
1160000          2
1840000          2
1095000          2
193000           2
895000           2
10500000         2
315000           2
532000           2
2340000          2
303800           2
665000           2
531100           2
804              2
235000           2
2079087          2
1770000          2
1875000          2
602000           2
864700           2
1288000          2
1440000          2
4250000          2
1995000          2
759000           2
487000           2
1203111          2
3730000          2
208800           2
1275000          2
676500           2
324000           2
902406           2
1224000          2
313000           2
2820000          2
4150000          2
1159000          2
706906           2
175000           2
376000           2
1068000          2
2499950          2
1955000          2
715000           2
888000           2
7600000          2
3975000          2
1006720          2
3225000          2
555600           2
1360000          2
14500000         2
837000           2
40000000         2
342000           2
219450           2
436295           2
2920000          2
2975000          2
3805000          2
7750000          2
3882281          2
645750           2
822800           2
445000           2
2325000          2
995000           2
3220100          2
592800           2
854              2
3350000          2
160000           2
6918000          2
639000           2
2140000          2
4237015          2
1323183          2
127000           2
110000           2
17823000         2
220000           2
760500           2
1755000          2
1175000          2
9800000          2
120000           2
789000           2
2835000          2
642000           2
314000           2
855000           2
5350000          2
3360000          2
1472240          2
1464000          2
751801           2
4900000          2
2930000          2
3650000          2
341000           2
1475000          2
417000           2
604000           2
3018600          2
987000           2
1426011          2
1127125          2
6400000          2
3545000          2
2497795          2
1285000          2
10543000         2
565000           2
1511120          2
614400           2
1562400          2
1124000          2
8600000          2
176000           2
663670           2
80000            2
314900           2
1575000          2
686750           2
1490000          2
821358           2
872300           2
190000           2
1174854          2
2115000          2
880000           2
274596           2
1856250          2
1820000          2
796280           2
1782381          2
1070000          2
1035125          2
985320           2
1510000          2
997500           2
2660000          2
5160000          2
452000           2
3323500          2
900450           2
5900000          2
319200           2
534000           2
2680000          2
12500000         2
4175000          2
40               2
6225000          2
724000           2
813100           2
1005000          2
224750           2
1297000          2
5200000          2
713000           2
2050000          2
496000           2
7200000          2
433350           2
1083780          2
612856           2
785610           2
1932000          2
480000           2
970418           2
849045           2
2070000          2
765000           2
468750           2
1277200          2
1135000          2
653800           2
1173075          2
5315000          2
264000           2
4734000          2
1073250          2
548000           2
679600           2
2805600          2
3573000          2
1080000          2
5040000          2
11782000         1
3462000          1
4706370          1
2734577          1
6706874          1
271250           1
379667           1
611310           1
7                1
12459000         1
12332606         1
218400           1
1660500          1
1011780          1
542500           1
824234           1
551000           1
3374500          1
8243750          1
10880000         1
779000           1
4133155          1
3294331          1
4280000          1
338000           1
385605           1
1520194          1
810700           1
1052000          1
878000           1
800550           1
183443           1
4893360          1
552000           1
2280000          1
972100           1
7100000          1
630500           1
1055000          1
1925000          1
1070700          1
1255000          1
5011400          1
284200           1
3120000          1
326950           1
1167450          1
674000           1
579481           1
3670000          1
1710000          1
951316           1
4440000          1
211256           1
2850935          1
499175           1
4126000          1
2182750          1
3590000          1
4372000          1
2912000          1
1500600          1
7561626          1
721700           1
4904600          1
2529600          1
893500           1
1507600          1
177157           1
10162500         1
536310           1
4526530          1
643871           1
379500           1
1050725          1
2214746          1
711000           1
1665000          1
297837           1
904800           1
951187           1
9915000          1
406900           1
159000           1
3242800          1
359700           1
8798000          1
10060000         1
1188887          1
4030000          1
674449           1
782000           1
2759000          1
1940000          1
3855000          1
470000           1
1315000          1
1560300          1
319000           1
1038180          1
1230075          1
299000           1
6600000          1
1473232          1
917000           1
403150           1
2315000          1
280800           1
730800           1
8905580          1
334000           1
2470000          1
2019598          1
1988800          1
4202500          1
3344200          1
1449450          1
1011111          1
514800           1
1405000          1
1540000          1
2076000          1
1758000          1
159200           1
1466200          1
597000           1
663000           1
1691100          1
363400           1
1480000          1
852400           1
538200           1
387500           1
16169595         1
108000           1
191000           1
10093000         1
274000           1
297500           1
4664900          1
6900000          1
367873           1
747817           1
581250           1
337300           1
443700           1
819000           1
1679900          1
467500           1
517440           1
799800           1
3011536          1
3339000          1
1162500          1
6606016          1
4817400          1
5992000          1
29430000         1
4980000          1
20500000         1
5425000          1
452566           1
777000           1
1706250          1
5468000          1
7112             1
1659000          1
725760           1
690374           1
1990000          1
5241650          1
725685           1
803500           1
1318600          1
22966000         1
1242400          1
659430           1
889000           1
1076040          1
7245000          1
5816000          1
748020           1
3272000          1
2914500          1
338700           1
741959           1
419400           1
336750           1
654983           1
946000           1
877950           1
185000           1
1093000          1
3460000          1
259100           1
6850000          1
1090000          1
192150           1
65000            1
7354000          1
1605000          1
1519450          1
353175           1
923875           1
484000           1
1074919          1
2330000          1
4526000          1
3652000          1
8800000          1
334200           1
382800           1
1210150          1
637290           1
641950           1
5129810          1
241750           1
7770000          1
207500           1
2222500          1
507400           1
976800           1
665690           1
1387500          1
3840000          1
1326265          1
6297575          1
1264000          1
5686000          1
506992           1
2487726          1
3648700          1
866750           1
735200           1
432171           1
4967683          1
847300           1
3320901          1
2940000          1
137500           1
4389000          1
3065100          1
823350           1
1074000          1
522600           1
1271500          1
1559181          1
10599999         1
1484050          1
675700           1
8450000          1
553700           1
4728128          1
819500           1
1548000          1
4357000          1
484100           1
567500           1
6200000          1
4795700          1
682000           1
6100000          1
539000           1
838950           1
4744241          1
1050827          1
2563200          1
8919040          1
1965288          1
516289           1
578000           1
1466192          1
5376             1
3927108          1
1408500          1
3154200          1
2137900          1
6300000          1
1931700          1
622200           1
49000            1
593400           1
1155000          1
44502            1
354250           1
1203000          1
1380000          1
1445000          1
627700           1
1256000          1
1201176          1
8300000          1
773749           1
60               1
5295500          1
157100           1
533000           1
1028700          1
1268000          1
4787850          1
3663000          1
812000           1
532500           1
1123750          1
1220500          1
968803           1
915200           1
915212           1
177000           1
228000           1
2477500          1
78000            1
1313000          1
4058590          1
2552742          1
499500           1
3616550          1
478800           1
704000           1
1227500          1
1991500          1
698250           1
12725863         1
826000           1
543750           1
1514000          1
1904000          1
2029136          1
1029420          1
13771292         1
551542           1
704100           1
285000           1
476050           1
1211116          1
2192650          1
13005000         1
689800           1
1756800          1
4725000          1
1501000          1
13958260         1
467200           1
456550           1
2232750          1
543895           1
901194           1
677400           1
510700           1
687500           1
877000           1
205000           1
8225000          1
658000           1
1006000          1
1444050          1
9700000          1
399000           1
1720000          1
4070000          1
5750000          1
33905700         1
1110454          1
498394           1
488250           1
1912714          1
280500           1
855400           1
658900           1
2963000          1
1416700          1
752000           1
515000           1
310000           1
343000           1
1010000          1
2195000          1
6034110          1
10542000         1
674531           1
912880           1
302500           1
1709500          1
791000           1
3895000          1
7700000          1
792741           1
1960350          1
2790000          1
4653500          1
1656000          1
1073000          1
334500           1
766000           1
189580           1
4379000          1
2282080          1
876375           1
498960           1
1287500          1
2068000          1
1827000          1
116              1
4748526          1
311450           1
14358132         1
768750           1
385              1
276000           1
2490000          1
2168842          1
1420500          1
414500           1
2130000          1
1370000          1
728250           1
939120           1
555000           1
2275000          1
2151000          1
8697000          1
1257750          1
756000           1
981225           1
1235547          1
794000           1
4413000          1
14892400         1
6178485          1
719100           1
1742993          1
386000           1
324473           1
975150           1
1339000          1
9500000          1
4462000          1
2180000          1
723300           1
7900000          1
1228750          1
186000           1
1453056          1
1109619          1
1131000          1
989450           1
4720000          1
3883000          1
1341556          1
1340000          1
983250           1
16300000         1
1533000          1
2155000          1
2107620          1
8100000          1
29692000         1
832500           1
566850           1
1283400          1
21000000         1
1265569          1
355043           1
280600           1
1669600          1
1417500          1
3897700          1
827850           1
2620000          1
530400           1
1769600          1
3196980          1
987500           1
121000           1
2242128          1
1913150          1
2742921          1
13800000         1
1488619          1
1354000          1
573208           1
1134000          1
361000           1
829350           1
2348020          1
8900000          1
2133438          1
737491           1
2645000          1
787000           1
1773750          1
961695           1
2187000          1
13120800         1
140400           1
6137000          1
4216000          1
577000           1
1197700          1
3810000          1
612480           1
3504000          1
686627           1
905100           1
4275000          1
14800000         1
1136419          1
700417           1
709875           1
189000           1
4627000          1
5198700          1
6446900          1
981000           1
1404200          1
328000           1
1366200          1
1590800          1
1163448          1
2210000          1
5175240          1
559080           1
140000           1
4570960          1
9665121          1
69120            1
915000           1
1015000          1
1398250          1
1141650          1
461250           1
7400000          1
1370600          1
2260500          1
722000           1

#### cheack before save

In [919]:
Silver_df.isna().sum().sort_values(ascending=False)

down_payment      14401
district           4978
city               2127
available_from      586
price               462
bathrooms            68
bedrooms             67
compound             14
governorate          14
description           1
payment_method        0
type                  0
size_sqft             0
size_sqm              0
maid_room             0
bathrooms_plus        0
url                   0
dtype: int64

In [920]:
Silver_df[[
    "price",
    "size_sqft",
    "size_sqm",
    "bedrooms",
    "bathrooms",
    "down_payment"
]].describe()

,price,size_sqft,size_sqm,bedrooms,bathrooms,down_payment
count,"19,383.00","19,845.00","19,845.00","19,778.00","19,777.00","5,444.00"
mean,"16,414,932.73","11,137.07","1,034.67",2.98,2.95,"1,979,201.60"
std,"23,698,319.60","1,208,385.04","112,262.64",1.17,1.29,"3,866,547.91"
min,"186,900.00",215.00,20.00,0.00,1.00,1.00
25%,"6,000,000.00","1,367.00",127.00,2.00,2.00,"483,541.25"
50%,"10,345,550.00","1,830.00",170.00,3.00,3.00,"941,500.00"
75%,"18,161,726.50","2,594.00",241.00,4.00,4.00,"2,032,125.00"
max,"840,000,000.00","170,195,636.00","15,811,692.00",7.00,7.00,"150,000,000.00"

In [921]:
Silver_df["bathrooms_plus"].value_counts()

bathrooms_plus
False    19686
True       159
Name: count, dtype: Int64

In [922]:
Silver_df["maid_room"].value_counts()

maid_room
False    10505
True      9340
Name: count, dtype: Int64

In [923]:
Silver_df["payment_method"].value_counts()

payment_method
Cash            15519
Installments     3862
Unknown           464
Name: count, dtype: int64

In [924]:
Silver_df["type"].value_counts()

type
Apartment          8355
Chalet             4037
Villa              3569
Townhouse          1335
Twin House          834
Duplex              622
Penthouse           569
iVilla              268
Hotel Apartment     104
Land                 63
Cabin                38
Palace               23
Whole Building       14
Roof                  6
Full Floor            4
Bulk Sale Unit        3
Bungalow              1
Unknown               0
Name: count, dtype: int64

In [925]:
print(Silver_df["available_from"].min())
print(Silver_df["available_from"].max())

2023-06-14 00:00:00
2027-10-31 00:00:00

In [926]:
category_cols = [
    "type",
    "payment_method",
    "governorate"
]

for col in category_cols:
    Silver_df[col] = Silver_df[col].astype("category")

In [927]:
Silver_df.loc[
    Silver_df["available_from"] == Silver_df["available_from"].max(),
    ["available_from", "type", "price", "compound", "city"]
]

    available_from       type    price             compound            city
414     2027-10-31  Apartment  5000000  Al Thawra El Khadra  6 October City

In [928]:
Silver_df.loc[
    Silver_df["available_from"] >= "2027-01-01",
    ["available_from", "compound", "city", "price"]
].sort_values("available_from")

    available_from             compound            city    price
414     2027-10-31  Al Thawra El Khadra  6 October City  5000000

In [929]:
print("Earliest availability:", Silver_df["available_from"].min())
print("Latest availability:", Silver_df["available_from"].max())

Earliest availability: 2023-06-14 00:00:00
Latest availability: 2027-10-31 00:00:00

In [930]:
future = Silver_df[
    Silver_df["available_from"] > pd.Timestamp.today().normalize()
]

print(f"Future listings: {len(future)}")
future[["available_from", "compound", "city", "price"]].head()

Future listings: 114

,available_from,compound,city,price
50,2026-08-21,Atalantis,Hurghada,3017400
333,2026-08-31,Princess Resort,Hurghada,2240000
375,2026-08-12,Magawish Resort,Hurghada,3042000
380,2026-08-31,Ghazala Bay,NaN,13504000
390,2026-08-29,Mountain View 1.1,"The 5th Settlement, New Cairo City",26100000

In [931]:
print("Availability Date Range")
print("-----------------------")
print("Minimum:", Silver_df["available_from"].min())
print("Maximum:", Silver_df["available_from"].max())

future = Silver_df[
    Silver_df["available_from"] > pd.Timestamp.today().normalize()
]

print(f"\nFuture listings: {len(future)}")
print(f"Percentage: {len(future)/len(Silver_df)*100:.2f}%")

Availability Date Range
-----------------------
Minimum: 2023-06-14 00:00:00
Maximum: 2027-10-31 00:00:00

Future listings: 114
Percentage: 0.57%

In [932]:
Silver_df.head()

,url,price,description,type,available_from,payment_method,down_payment,compound,district,city,governorate,size_sqft,size_sqm,maid_room,bedrooms,bathrooms_plus,bathrooms
0,https://www.propertyfinder.eg/en/plp/buy/chale...,8000000,OWN A CHALET IN EL GOUNA WITH A PRIME LOCATION...,Chalet,2025-08-31,Cash,1200000,Swan Lake Gouna,Al Gouna,Hurghada,Red Sea,732,68,True,1,False,1
1,https://www.propertyfinder.eg/en/plp/buy/villa...,25000000,"For sale, a villa with immediate delivery in C...",Villa,2025-09-02,Cash,2100000,Karmell,New Zayed City,Sheikh Zayed City,Giza,2368,220,False,4,False,4
2,https://www.propertyfinder.eg/en/plp/buy/chale...,15135000,"With a down payment of EGP 1,513,000, a fully ...",Chalet,2025-08-19,Cash,1513000,Azha North,NaN,Ras Al Hekma,North Coast,1270,118,False,2,False,2
3,https://www.propertyfinder.eg/en/plp/buy/apart...,12652000,Own an apartment in New Cairo with a minimal d...,Apartment,2025-08-26,Installments,1260000,Taj City,5th Settlement Compounds,"The 5th Settlement, New Cairo City",Cairo,1787,166,False,3,False,2
4,https://www.propertyfinder.eg/en/plp/buy/villa...,45250000,"Project: Granville Location: Fifth Settlement,...",Villa,2025-09-02,Cash,2262500,Granville,NaN,New Capital City,Cairo,4306,400,False,7,False,7

### **Save Silver Layer**

In [933]:
Silver_df.to_csv(
    "/Users/folder/project_real_estate/data/raw/Silver.csv",
    index=False
)

print("Silver Layer Created Successfully")

Silver Layer Created Successfully